import { PortfolioCompany } from "@/common/type/portofolio-companny";

export const portfolioCompanies: PortfolioCompany[] = [
  {
    id: "d8c2345d-7bb1-4d29-9084-c6311dcaf8f3",
    slug: "ibm-indonesia",
    name: "PT. IBM Delivery Indonesia",
    role: "Application Developer",
    period: "2023 — 2026",
    location: "Jakarta, Indonesia",
    summary: "Application Developer at PT. Xsis Mitra Utama (now as Part of PT. IBM Delivery Indonesia).",
    description:
      "Currently assigned as a consultant for PT. Bank Raya Tbk. I specialize in building responsive and performant web applications using modern frameworks like React and Next.js, ensuring scalable and maintainable codebases for enterprise-level systems.",
    key_responsibilities: [
      "Develop and maintain responsive, interactive, and high-performance user interfaces (UIs) using frameworks such as Next Js include (React.js, Typescript, Tailwind, mobx, react hooks) and use MVVM.",
      "Develop or maintain legacy projects and create and design tables for the purposes of developing new features.",
      "Collaborate with the Backend team, UI/UX Designers, and QA Engineers to design, implement, and refine web-based application features. Efficiently integrate APIs and third-party services to support front-end functionality.",
      "Optimize applications for performance, cross-browser compatibility, and accessibility across various devices.",
      "Actively participate in sprint planning sessions, code reviews, and daily standups as part of the Agile/Scrum work methodology.",
      "Develop technical documentation to support long-term maintenance and onboarding new team members.",
      "Maintenance legacy project (ASP.NET)."
    ],
    image_url:"/assets/ibm/light-ibm.png",
    image_dark_url: "/assets/ibm/dark-ibm.svg",
    created_at: "2023-08-01",
    project_overview:"",
    project_team: [
      "Ahmad Yulia Rizky Fahmi",
      "Yusuf Ashari",
      "Muhammad Rifqy",
      "Ali Ridho",
      "Dwi Gunardi",
      "Rony Ardianto"
    ],
    assets: [
      {
        id: "839495f8-b0fa-4d6a-bcd1-eed971865f50",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/IFMIS/home.png",
        alt: "IFMIS",
        title: "IFMIS - Intergrated Financial Management Information System.",
        description: "Development of finance division information systems that include e-budgeting, procurement, switching, and value tracking.",
        tags: ["Development", "Dashboard", "UI", "Frontend", "Finance", "Procurement"],
        url: "#"
      },
      {
        id: "4cd17006-1c72-45df-990e-9e56e47542e4",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/SDB/home.png",
        alt: "Safe Deposit Box",
        title: "SDB - Safe Deposit Box",
        description: "Development of safekeeping services for valuables or important documents provided by banks to customers in the form of safety deposit boxes.",
        tags: ["Development", "Dashboard", "UI", "Frontend"],
        url: "#"
      },
      {
        id: "2f759411-7891-44e3-a2e8-ce3fcb3198c2",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/Arsy/detail_bank_soal_page.png",
        alt: "Arsy",
        title: "Arsy",
        description: "Development of bank question creation services for questions every time a user logs into the company's main website.",
        tags: ["Development", "Dashboard", "UI", "Frontend"],
        url: "#"
      },
      {
        id: "15da9a62-ef70-4df9-8c07-4fdb0dee11c6",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/Rayment/home.png",
        alt: "Raya Document",
        title: "Raya Document",
        description: "Development of Credit Document Digitalization Management.",
        tags: ["Development", "Dashboard", "UI", "Frontend"],
        url: "#"
      },
      {
        id: "5ec10962-7885-4a89-99bd-c1a5091755a3",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/E-Recruitment/after-form-evaluasi.png",
        alt: "E-Recruitment",
        title: "E-Recruitment",
        description: "Makes it easy to create a recruitment process from the beginning to the end, starting from entering your CV, interview, psychological test, medical check up and recruitment.",
        tags: ["Development", "Dashboard", "UI", "Frontend"],
        url: "#"
      },
      {
        id: "ac656af8-c850-41d3-b478-aa14f9377bc7",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/Dashboard-Refund/db-refund.jpeg",
        alt: "Dashboard Refund",
        title: "Dashboard Refund",
        description: "Dashboard for refund and reconciliation.",
        tags: ["Maintenance", "Dashboard", "UI", "Frontend"],
        url: "#"
      },
      {
        id: "fc7a2270-b213-4871-88aa-876559c7bfec",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/Isdm/SS-2652 after handle id.png",
        alt: "isdm",
        title: "ISDM - Integrated System Human Resources Information System",
        description: "Legacy Project, and information system that covers internal employee activities, such as leave, payroll, employee lists, benefits, etc.",
        tags: ["Maintenance", "Dashboard", "UI", "Frontend", "Backend", "Fullstack"],
        url: "#"
      },
      {
        id: "6026e3a2-f53f-4081-88e3-72337f6bfb4b",
        company_id:"raya-1",
        company_name:"Bank Raya",
        src: "/assets/raya/Rcsa/rcsa.jpeg",
        alt: "rcsa",
        title: "Risk Management System",
        description: "Legacy Project, and information system that includes information about company management risks and anti-fraud.",
        tags: ["Maintenance", "Dashboard", "UI", "Frontend", "Backend", "Fullstack"],
        url: "#"
      },
    ],
  },
  {
    id: "6b5abdd1-7ee7-44a5-bfdf-a6097af03af5",
    slug: "established-jakarta",
    name: "Established Jakarta",
    role: "Fullstack Developer",
    period: "Dec 2021 — Dec 2023",
    location: "Jakarta Selatan, Indonesia",
    summary: "Full Stack Developer at Established Jakarta.",
    description:
      "Working on digital experiences for various types of company profiles, dashboards, and visual communications for their website and product information.",
    key_responsibilities: [
      "Build Microservices API using Laravel, Docker.",
      "Normalize Database using Postgresql, and Create Database Transaction.",
      "Create Content Management Syatem.",
      "Develop and maintain responsive, interactive, and high-performance user interfaces (UI) include web company profile and content management system using frameworks such as Next Js include (React.js, Typescript, Tailwind, mobx, react hooks).",
      "Testing website in staginq mode (Development Mode) also Maintenance source code from develop to production (QA)",
      "collaboration with the SEO team for Technical SEO.",
      "Project Management (Create Ticket and DoD Description on ClickUp)."
    ],
    image_url:"/assets/established-jakarta/estb-logo.ico",
    image_dark_url: "/assets/established-jakarta/estb-logo.ico",
    created_at: "2023-01-01T00:00:00.000Z",
    project_overview:"",
    project_team: [
      "R Andika",
      "Muhammad Khotib",
    ],
    assets: [
      {
        id: "792261d0-82dc-4747-8a97-b93f8fdff6d7",
        company_id:"estb-1",
        company_name:"PT Gemma Natura Lestari",
        src: "/assets/established-jakarta/estb-gnl.png",
        alt: "GNL",
        title: "PT Gemma Natura Lestari",
        description: "PT Gemma Natura Lestari is a manufacturing company that produces and formulates cosmetic, personal care products. We are improving service quality for mutual benefit.",
        tags: ["Development", "UI", "Frontend", "Typescript", "Backend", "Next.js", "Laravel", "PostgreSql", "Emotion", "Docker", "Nginx"],
        url: "https://gnl.co.id/"
      },
      {
        id: "e8301431-821b-4a12-9dda-91120f75a318",
        company_id:"etsb-1",
        company_name:"PT. ABADINUSA USAHASEMESTA",
        src: "/assets/established-jakarta/estb-abadinusa.png",
        alt: "abadi nusa",
        title: "PT. ABADINUSA USAHASEMESTA",
        description: "AbadiNusa as a trusted distributor in the healthcare industry, committed to giving nothing short of world-class standards in medical technology, intelligent devices.",
        tags: ["Project Management", "Next.js", "Typescript", "Golang", "Emotion", "Amazon Web Service"],
        url: "https://www.abadinusa.co.id",
      },
      {
        id: "cdc803f6-1851-476b-8c46-3bfc553c2fbc",
        company_id:"estb-1",
        company_name:"Established Jakarta",
        src: "/assets/established-jakarta/estb-system-internal.png",
        alt: "Established Jakarta",
        title: "Employee Activity Internal System",
        description: "The internal system is a system that accommodates employees to report their daily work. Such as making timesheets, client management, project management, and employee management. Here there is also role management and access for each user.",
        tags: ["Dashboard", "UI", "Frontend", "Backend", "API", "Laravel", "PostgreSql", "Docker", "Nginx", "Ubuntu"],
        url: "#",
      },
      {
        id: "160c252c-96db-447e-a8ed-27895624bc6f",
        company_id:"estb-1",
        company_name:"Established Jakarta",
        src: "/assets/established-jakarta/estb-digital.png",
        alt: "ESTB Digital",
        title: "ESTB Digital",
        description: "ESTB Digital is part of web Established Jakarta. Specializing in creating a data-based digital marketing strategy for your business. CMS management is also made for data content management.",
        tags: ["Dashboard", "UI", "Frontend", "Next.js", "Typescript", "Backend", "API", "Laravel", "PostgreSql", "Docker", "Nginx", "Ubuntu"],
        url: "#",
      },
      {
        id: "459bec25-1cf2-48b7-8713-9b815a82eeeb",
        company_id:"estb-1",
        company_name:"Established Jakarta",
        src: "/assets/established-jakarta/estb-website.png",
        alt: "ESTB Website",
        title: "ESTB Website",
        description: "Company profile that contains services offered for digital marketing needs, social media content, and strategic research. CMS management is also made for data content management.",
        tags: ["Dashboard", "UI", "Frontend", "Next.js", "Typescript", "Backend", "API", "Laravel", "PostgreSql", "Docker", "Nginx", "Ubuntu"],
        url: "#",
      },
    ],
  },
  {
    id: "6b5abdd1-7ee7-44a5-bfdf-a6097af03af5",
    slug: "freelance",
    name: "Self-Employed",
    role: "Software Engineer",
    period: "Dec 2021 — Now",
    location: "Jakarta Selatan, Indonesia",
    summary: "Full-Stack Software Engineer | Website Development & Server Migration",
    description:
      "According to the patient's case",
    key_responsibilities: [
      "Custom Website Development (HTML/CSS/JS, Next.js/React.js, Nuxt.js/Vue.js, Svelte, Python/Django/Flask, PHP/Laravel, and based on the case as needed)",
      "Server Migration & Deployment (Vercel, Railway, PythonAnywhere, AWS, DigitalOcean, GoDaddy, and based on the case as needed)",
      "ML Model Integration (TensorFlow LSTM, NLTK NLP)",
      "DevOps Automation (GitHub Actions, CI/CD, Docker)"
    ],
    image_url:"/assets/self-employe.jpeg",
    image_dark_url:"/assets/self-employe.jpeg",
    created_at: "2023-01-01T00:00:00.000Z",
    project_overview:"",
    project_team: [],
    assets: [
      {
        id: "792261d0-82dc-4747-8a97-b93f8fdff6d7",
        company_id:"raak-1",
        company_name:"#BersikhkanIndonesia",
        src: "/assets/freelance/freelance-bersihkan.png",
        alt: "#BersikhkanIndonesia",
        title: "#BersikhkanIndonesia",
        description: "#BersihkanIndonesia is a coalition of civil society organizations that aims to encourage Indonesians to actively advocate for changes in energy, economic, and environmental policies. Key of responsibilities: Migrate website (Wordpress) from server third party (CPanel) to server stackholder (Ubuntu) and the website runs on a container environment (Docker, Nginx) also change domain.",
        tags: ["Migration", "Docker", "Nginx", "Ubuntu", "BASH"],
        url: "https://bersihkanindonesia.org/"
      },
      {
        id: "3b839a6f-feb4-40bd-9b2e-22309c6e0c68",
        company_id:"raak-1",
        company_name:"PT DCI Indonesia Tbk (DCII)",
        src: "/assets/freelance/freelance-dci.png",
        alt: "PT DCI Indonesia Tbk (DCII)",
        title: "DCI Indonesia Annual Report",
        description: "DCI Indonesia is proud to announce that it is now a Certified B Corporation, the first data center colocation company in Asia to achieve the certification.",
        tags: ["Development", "Next.js", "Emotion", "Docker", "Nginx", "Typescript", "Amazon Web Service"],
        url: "#",
      },
      {
        id: "cdc803f6-1851-476b-8c46-3bfc553c2fbc",
        company_id:"raak-1",
        company_name:"Yayasan Cerah Indonesia",
        src: "/assets/freelance/freelance-cerah.png",
        alt: "Yayasan Cerah Indonesia",
        title: "Yayasan Cerah Indonesia",
        description: "Yayasan Indonesia Cerah also known as CERAH is an Indonesian non-profit organization working to advance the energy transition policy agenda in Indonesia.",
        tags: ["Development", "Next.js", "Emotion", "laravel", "Docker", "Nginx", "Typescript", "Amazon Web Service"],
        url: "https://www.cerah.or.id/",
      },
    ],
  },
  {
    id: "4fd1b397-bdd8-4e14-9658-e2933e143c68",
    slug: "fun-project",
    name: "Fun Project",
    role: "whatever I want",
    period: "Now",
    location: "Jakarta Selatan, Indonesia",
    summary: "Web Application | Data Science | AI/ML | Data Engineer",
    description:
      "Guess What?",
    key_responsibilities: [
      "Self Service",
    ],
    image_url:"/assets/self-employe.jpeg",
    image_dark_url:"/assets/hc-cat.jpg",
    created_at: "2023-01-01T00:00:00.000Z",
    project_overview:"",
    project_team: [],
    assets: [
      {
        id: "8cb89a6e-f7fb-4291-b7d4-f1cbc121497c",
        company_id:"raak-fun-1",
        company_name:"Fun Project",
        src: "/assets/freelance/tugasakhir.jpg",
        alt: "Implementasi Long Short-Term Memory untuk Identifikasi Berita Hoax Berbahasa Inggris pada Media Sosial",
        title: "Implementasi Long Short-Term Memory untuk Identifikasi Berita Hoax Berbahasa Inggris pada Media Sosial",
        description: "This is project implementation Long Short-Term Memory untuk Identifikasi Berita Hoax Berbahasa Inggris pada Media Sosial.",
        tags: ["Python", "Flask", "Deep Learning", "Machine Learning", "NLP", "TensorFlow", "Keras", "Long-Short Term Memory"],
        url: "https://github.com/rakagemi/IDENTIFYING-HOAX-NEWS"
      },
    ],
  }
];